spring:
  config:
    activate:
      on-profile: development
  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: update