# logging
logging:
  level:
    org.springframework: INFO
    com.mkyong: INFO
    com.zaxxer: INFO
    root: INFO


spring:
  datasource:
    url: ${dateman.JDBC_DATABASE_URL}
    username: ${dateman.JDBC_DATABASE_USERNAME}
    password: ${dateman.JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

    # default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ

      security:
        basic:
          enabled: false


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${dateman.DATEMAN_GMAIL_USERNAME}
    password: ${dateman.DATEMAN_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true

server:

  ssl:
    enabled: false
    key-store: classpath:dateman_backend_keystore.p12
    key-store-password: ${dateman.DATEMAN_KEYSTORE_PASSWORD}
    key-store-type: pkcs12
    key-alias: dateman-key
    key-password: ${dateman.DATEMAN_KEYSTORE_PASSWORD}

  port : ${PORT:8443}
  #http-redirect-port: 8081

