# logging
logging:
  level:
    org.springframework: INFO
    com.mkyong: INFO
    com.zaxxer: INFO
    root: INFO


spring:
  datasource:
    url: ${clieman.JDBC_DATABASE_URL}
    username: ${clieman.JDBC_DATABASE_USERNAME}
    password: ${clieman.JDBC_DATABASE_PASSWORD}

    # default connection pool
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ

      security:
        basic:
          enabled: false


  mail:
    host: ${clieman.EMAIL_HOST}
    port: ${clieman.EMAIL_PORT}
    username: ${clieman.EMAIL_USERNAME}
    password: ${clieman.EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: ${clieman.EMAIL_HOST}
          starttls:
            enable: true

server:

  port : ${PORT:8443}
  #http-redirect-port: 8081